---
title: Zend een signaal in Scratch
hero_image: afbeeldingen / banner.png
description: Leer hoe je een bericht kunt zenden waarop verschillende sprites kunnen reageren
listed: false
ingredient: true
copyedit: true
steps:
  - 
    title: Inleiding
