---
title: Scratch এ একটি বার্তা সম্প্রচার করুন
hero_image: images/banner.png
description: এমন কিছু বার্তা সম্প্রচার করতে শিখুন যা কাজ করবে বিভিন্ন sprite এর দ্বারা
listed: false
ingredient: true
copyedit: true
steps:
  - title: ভূমিকা
