---
title: Scratch-இல் ஒரு செய்தியை ஒலிபரப்பவும்
hero_image: images/banner.png
description: வெவ்வேறு Sprite-களின் மூலம் செயல்படக்கூடிய ஒரு செய்தியை எவ்வாறு ஒலிபரப்பலாம்(வலைபரப்பு/broadcast) என்பதை அறிக
listed: false
ingredient: true
copyedit: true
steps:
  - title: அறிமுகம்
