---
title: Send en melding i Scratch
hero_image: images/banner.png
description: Lær hvordan du sender en melding som kan få andre figurer til å gjøre noe
listed: false
ingredient: true
copyedit: true
steps:
  - 
    title: Introduksjon
