---
title: Phát một tin nhắn trong Scratch
hero_image: images/banner.png
description: Tìm hiểu cách phát một tin nhắn có thể được tác động bởi các đồ họa khác nhau
listed: false
ingredient: true
copyedit: true
steps:
  - 
    title: Giới thiệu
