---
title: Send en besked i Scratch
hero_image: images/banner.png
description: Lær hvordan man sender en meddelelse, der kan udføres af flere forskellige sprites
listed: false
ingredient: true
copyedit: true
steps:
  - 
    title: Introduktion
