---
title: Difundir uma mensagem no Scratch
hero_image: images/banner.png
description: Aprende como difundir uma mensagem que pode ser executada por diferentes actores
listed: false
ingredient: true
copyedit: true
steps:
  - 
    title: Introdução
