---
title: Slanje poruke u Scratchu
hero_image: images/banner.png
description: Saznaj kako poslati poruku na koju mogu reagirati razliÄiti likovi
listed: false
ingredient: true
copyedit: true
steps:
  - 
    title: Uvod
