---
title: Slanje poruke u Scratchu
hero_image: images/banner.png
description: Nauči kako poslati poruku na koju mogu reagirati različiti likovi
listed: false
ingredient: true
copyedit: true
steps:
  - 
    title: Uvod
