---
title: یک پیام در اسکرچ پخش کنید
hero_image: images/banner.png
description: یاد بگیرید چگونه یک پیام را پخش کنید که بتواند توسط شبح‌های مختلف مورد استفاده قرار بگیرد
listed: false
ingredient: true
copyedit: true
steps:
  - title: مقدمه
