---
title: I-broadcast ang isang mensahe sa Scratch
hero_image: mga imahe / banner.png
description: Alamin kung paano mag-broadcast ng isang mensahe na maaaring kumilos ng iba't ibang mga sprite
listed: false
ingredient: true
copyedit: true
steps:
  - 
    title: Panimula
