---
title: Enviar un mensaje en Scratch
hero_image: images/banner.png
description: Aprende a enviar un mensaje al que pueden reaccionar los diferentes objetos
listed: false
ingredient: true
copyedit: true
steps:
  - title: Introducción
