---
title: Darlledwch neges yn Scratch
hero_image: images/banner.png
description: Dysgu sut i ddarlledu neges y gall corluniau eraill weithredu arni
listed: false
ingredient: true
copyedit: true
steps:
  - 
    title: Cyflwyniad
