---
title: Senden einer Nachricht in Scratch
hero_image: images/banner.png
description: So kannst du eine Nachricht senden, auf die verschiedene Figuren reagieren können
listed: false
ingredient: true
copyedit: true
steps:
  - title: Einleitung
