---
title: Transmiterea unui mesaj în Scratch
hero_image: images/banner.png
description: Învață cum să transmiți un mesaj în funcție de care pot acționa diferite personaje
listed: false
ingredient: true
copyedit: true
steps:
  - 
    title: Introducere
