---
title: Transmita uma mensagem no Scratch
hero_image: images/banner.png
description: Aprenda como transmitir uma mensagem que pode ser executada por diferentes atores
listed: false
ingredient: true
copyedit: true
steps:
  - 
    title: Introdução
