---
title: Transmet un missatge a Scratch
hero_image: images/banner.png
description: Obteniu informació sobre com emetre un missatge que es pot aplicar per diferents sprites. Make a correction
listed: false
ingredient: true
copyedit: true
steps:
  - 
    title: Introducció
