---
title: Objavi sporo훾ilo v Scratchu
hero_image: images/banner.png
description: Nau훾i se objavljati sporo훾ila, na katere se lahko odzovejo razli훾ne figure
listed: false
ingredient: true
copyedit: true
steps:
  - 
    title: Uvod
