---
title: Vyšli zprávu ve Scratchi
hero_image: images/banner.png
description: Nauč se vyslat zprávu, na kterou mohou reagovat různé postavy
listed: false
ingredient: true
copyedit: true
steps:
  - 
    title: Úvod
