---
title: Küldj üzenetet Scratchben
hero_image: images/banner.png
description: Tanuld meg, hogyan küldhetsz egy üzenetet, amelyre különböző szereplők reagálhatnak
listed: false
ingredient: true
copyedit: true
steps:
  - title: Bevezetés
