---
title: Scratch ನಲ್ಲಿ ಸಂದೇಶವನ್ನು broadcast (ಪ್ರಸಾರ) ಮಾಡಿ
hero_image: images/banner.png
description: ವಿಭಿನ್ನ ಸ್ಪ್ರೈಟ್‌ಗಳಿಂದ ಕಾರ್ಯನಿರ್ವಹಿಸಬಹುದಾದ ಸಂದೇಶವನ್ನು ಹೇಗೆ broadcast (ಪ್ರಸಾರ) ಮಾಡುವುದು ಎಂದು ತಿಳಿಯಿರಿ
listed: false
ingredient: true
copyedit: true
steps:
  - title: ಪರಿಚಯ
