---
title: Transmitir un mensaje en Scratch
hero_image: images/banner.png
description: Aprende a transmitir un mensaje al que pueden reaccionar los diferentes objetos
listed: false
ingredient: true
copyedit: true
steps:
  - title: Introducción
