---
title: Sõnumi ülekandmine Scratchis
hero_image: images/banner.png
description: Vaata, kuidas kanda üle sõnumit eri spraitidele käsklusi andes
listed: false
ingredient: true
copyedit: true
steps:
  - 
    title: Sissejuhatus
