---
title: Nadaj komunikat w Scratchu
hero_image: images/banner.png
description: Dowiedz się, jak nadać komunikat, który może być obsłużony przez różne duszki
listed: false
ingredient: true
copyedit: true
steps:
  - 
    title: Wprowadzenie
