---
title: Vysielanie správy v jazyku Scratch
hero_image: obrazky/banner.png
description: Naučte sa vysielať správu, na ktorú môžu reagovať rôzne postavy
listed: false
ingredient: true
copyedit: true
steps:
  - 
    title: Úvod
