---
title: Envoie un message à tous dans Scratch
hero_image: images/banner.png
description: Apprends à envoyer un message auquel plusieurs lutins pourront réagir
listed: false
ingredient: true
copyedit: true
steps:
  - 
    title: Introduction
