---
title: Envoie un message à tous dans Scratch
hero_image: images/banner.png
description: Apprends à diffuser un envoi à tous sur lequel différents sprites peuvent réagir
listed: false
ingredient: true
copyedit: true
steps:
  - 
    title: Introduction
