---
title: Envoie un message à tous dans Scratch
hero_image: images/banner.png
description: Learn how to broadcast a message which can be acted upon by different sprites
listed: false
ingredient: true
copyedit: true
steps:
  - 
    title: Introduction
