---
title: Scratch'da bir mesaj yayınla
hero_image: images/banner.png
description: Farklı kuklaların kullanabileceği bir mesajı yayınlamayı öğrenin
listed: false
ingredient: true
copyedit: true
steps:
  - title: Giriş
